
import LocalizedStrings from 'react-native-localization';

let strings = new LocalizedStrings({
    //English lang...
    "en-US":{
        in:"in the",
        buddha:"Buddha's",
        footsteps:"Footsteps",
        register: 'Register',
        signin: 'Sign In',
        email: 'Email',
        password: 'Password',
        confirmpassword: 'Confirm Password',
        couponcode: 'Coupon Code',
        home: 'Home',
        store:'Store',
        site:'All Sites',
        loading: 'Loading stores...',
        Footsteps: 'Footsteps',
        settings: 'Settings',
        forgot: 'Forgot Password?',
        cleardata: 'Clear Data',
        changelang: 'Change Language',
        changepass: 'Change Password',
        terms: 'Terms and Privacy Policy',
        signout: 'Sign Out',
        about: 'About',
    },
    // Spanish lang...
    en:{
        in:"en el",
        buddha:"Buda",
        footsteps:"Pasos",
        register: 'Registro',
        signin: 'Registrarse',
        email: 'Email',
        password: 'Contraseña',
        confirmpassword: 'Confirmar contraseña',
        couponcode: 'Código promocional',
        home: 'Casa',
        store: 'Almacenar',
        site:'Todos los sitios',
        loading: 'Cargando tiendas...',
        Footsteps: 'Pasos',
        settings : 'Ajustes',
        forgot: '¿Se te olvidó tu contraseña?',
        cleardata: 'Borrar datos',
        changelang: 'Cambiar idioma',
        changepass: 'Cambia la contraseña',
        terms: 'Términos y Política de Privacidad',
        signout: 'Desconectar',
        about: 'Acerca de',
    },
    // French lang....
    it: {
        in:"dans le",
        buddha:"Bouddha",
        footsteps:"trace de pas",
        register: 'Registre',
        signin: 'Se connecter',
        email: 'Email',
        password: 'Mot de passe',
        confirmpassword: 'Confirmez le mot de passe',
        couponcode: 'Code de coupon',
        home: 'Accueil',
        store:'le magasin',
        site: 'Tous les sites',
        loading: 'Chargement des magasins...',
        Footsteps: 'trace de pas',
        settings: 'Paramètres',
        forgot: 'Mot de passe oublié?',
        cleardata: 'Effacer les données',
        changelang: 'Changer de langue',
        changepass: 'Changer le mot de passe',
        terms: 'Termes et politique de confidentialité',
        signout: 'Déconnexion',
        about: 'Sur',
    }
});

module.exports = strings;
