
import LocalizedStrings from 'react-native-localization';

let strings = new LocalizedStrings({
    //English lang...
    "en-US":{
        in:"in the",
        buddha:"Buddha's",
        footsteps:"footsteps",
        register: 'Register',
        signin: 'Sign In',
        email: 'Email',
        password: 'Password',
        confirmpassword: 'Confirm Password',
        couponcode: 'Coupon Code',
        home: 'Home',
        store:'Store',
        site:'All Sites',
        loading: 'Loading stores...',
        Footsteps: 'Footsteps',
        settings: 'Settings',
        forgot: 'Forgot Password?',
        cleardata: 'Clear Data',
        changelang: 'Change Language',
        changepass: 'Change Password',
        terms: 'Terms and Privacy Policy',
        signout: 'Sign Out',
        about: 'About',
    },
    // Spanish lang...
    en:{
        in:"en el",
        buddha:"Buda",
        footsteps:"pasos",
        register: 'Registro',
        signin: 'Registrarse',
        email: 'Email',
        password: 'Contraseña',
        confirmpassword: 'Confirmar contraseña',
        couponcode: 'Código promocional',
        home: 'Casa',
        store: 'Almacenar',
        site:'Todos los sitios',
        loading: 'Cargando tiendas...',
        Footsteps: 'Pasos',
        settings : 'Ajustes',
        forgot: '¿Se te olvidó tu contraseña?',
        cleardata: 'Borrar datos',
        changelang: 'Cambiar idioma',
        changepass: 'Cambia la contraseña',
        terms: 'Términos y Política de Privacidad',
        signout: 'Desconectar',
        about: 'Acerca de',
    },
    // French lang....
    it: {
        in:"dans le",
        buddha:"Bouddha",
        footsteps:"trace de pas",
        register: 'Registre',
        signin: 'Se connecter',
        email: 'Email',
        password: 'Mot de passe',
        confirmpassword: 'Confirmez le mot de passe',
        couponcode: 'Code de coupon',
        home: 'Accueil',
        store:'le magasin',
        site: 'Tous les sites',
        loading: 'Chargement des magasins...',
        Footsteps: 'trace de pas',
        settings: 'Paramètres',
        forgot: 'Mot de passe oublié?',
        cleardata: 'Effacer les données',
        changelang: 'Changer de langue',
        changepass: 'Changer le mot de passe',
        terms: 'Termes et politique de confidentialité',
        signout: 'Déconnexion',
        about: 'Sur',
    },
    // Russian lang....
    rs: {
        in:"в",
        buddha:"Будда",
        footsteps:"шаги",
        register: 'регистр',
        signin: 'Войти в систему',
        email: 'Эл. адрес',
        password: 'пароль',
        confirmpassword: 'Подтвердите Пароль',
        couponcode: 'код купона',
        home: 'Главная',
        store:'хранить',
        site: 'Все сайты',
        loading: 'Загрузка магазинов ...',
        Footsteps: 'шаги',
        settings: 'настройки',
        forgot: 'Забыли пароль?',
        cleardata: 'Очистить данные',
        changelang: 'Изменить язык',
        changepass: 'Изменить пароль',
        terms: 'Условия и политика конфиденциальности',
        signout: 'Выход',
        about: 'Около',
    },
    //Chinese lang....
    ch: {
        in:"在里面",
        buddha:"佛",
        footsteps:"步伐",
        register: '寄存器',
        signin: '签到',
        email: '电子邮件',
        password: '密码',
        confirmpassword: '确认密码',
        couponcode: '优惠券代码',
        home: '家',
        store:'商店',
        site: '所有网站',
        loading: '加载商店...',
        Footsteps: '步伐',
        settings: '设置',
        forgot: '忘记密码？',
        cleardata: '清除数据',
        changelang: '改变语言',
        changepass: '更改密码',
        terms: '条款和隐私政策',
        signout: '登出',
        about: '关于',
    },
});

module.exports = strings;
